[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"

[nixpacks]
node-version = "20"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
